-- Trading signals generated by Python
CREATE TABLE IF NOT EXISTS signals (
    id            SERIAL PRIMARY KEY,
    ticker        TEXT NOT NULL REFERENCES contracts(ticker),
    source        TEXT NOT NULL,          -- 'weather', 'crypto', etc.
    side          TEXT NOT NULL,           -- 'yes' or 'no'
    edge          REAL NOT NULL,
    confidence    REAL NOT NULL,
    model_prob    REAL,
    market_price  REAL,
    created_at    TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_signals_ticker ON signals(ticker);
CREATE INDEX idx_signals_created ON signals(created_at);
